- name: Add OpenShift and OpenStack entries to /etc/hosts
  become: true
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    create: true
    state: present
    mode: '0644'
  loop: "{{ prelude_host_entries }}"
