- name: Install Openstack SIG repo
  ansible.builtin.package:
    name: centos-release-openstack-bobcat
    state: present
  when: os_migrate_virt_v2v|default(false)|bool

- name: Make sure required package are installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - libvirt
    - virt-v2v
    - qemu-kvm
    - python3
    - python3-pip
    - wget

- name: Gather installed package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Check virtio-win version
  ansible.builtin.fail:
    msg: "The package virtio-win is not installed or the version is lower than 1.9.40"
  when:
    - "'virtio-win' not in ansible_facts.packages or ansible_facts.packages['virtio-win'][0].version is version('1.9.40', '<')"

- name: Install openstacksdk
  ansible.builtin.pip:
    name: openstacksdk>1.0.0

- name: Install openstack client
  ansible.builtin.package:
    name: python3-openstackclient
    state: present
  when: os_migrate_virt_v2v|default(false)|bool

- name: Check if vmware-vix-disklib is present
  ansible.builtin.dnf:
    name: vmware-vix-disklib
    state: present
  check_mode: true
  register: vmware_vix_disklib_installed
  ignore_errors: true
  changed_when: false

- name: Download VMware VIX DiskLib
  ansible.builtin.get_url:
    url: "{{ vmware_vix_disklib_url }}/{{ vmware_vix_disklib }}"
    dest: "/tmp/{{ vmware_vix_disklib }}"
    mode: '0644'
  when: vmware_vix_disklib_installed.rc != 0

- name: Install VMware VIX DiskLib
  ansible.builtin.dnf:
    name: "/tmp/{{ vmware_vix_disklib }}"
    state: present
    disable_gpg_check: true
  when: vmware_vix_disklib_installed.rc != 0

- name: Check if virt-v2v-in-place exists in libexec
  ansible.builtin.stat:
    path: /usr/libexec/virt-v2v-in-place
  register: libexec_stat

- name: Check if virt-v2v-in-place is in $PATH
  ansible.builtin.shell: "command -v virt-v2v-in-place || true"
  register: virt_in_path
  changed_when: false

- name: Copy /usr/libexec/virt-v2v-in-place to /usr/bin if not in $PATH
  ansible.builtin.copy:
    src: /usr/libexec/virt-v2v-in-place
    dest: /usr/bin/virt-v2v-in-place
    mode: '0755'
    remote_src: true
  when:
    - libexec_stat.stat.exists
    - virt_in_path.stdout == ""

- name: Create configuration directory .config/openstack
  ansible.builtin.file:
    mode: '0755'
    path: "~/.config/openstack"
    recurse: true
    state: directory

- name: Create os-migrate data dir
  ansible.builtin.file:
    mode: '0755'
    path: "{{ os_migrate_vmw_data_dir }}"
    state: directory
    recurse: true

- name: Set Openstack credentials clouds.yaml file
  ansible.builtin.copy:
    mode: '0600'
    src: "{{ os_migrate_clouds_path|default(os_migrate_vmw_data_dir ~ '/clouds.yaml') }}"
    dest: "~/.config/openstack/clouds.yaml"
  when: copy_openstack_credentials_to_conv_host|default(false)|bool
