namespace: os_migrate
name: vmware_migration_kit
version: 2.0.0
readme: README.md
authors:
  - Mathieu Bultel <mat.bultel@gmail.com>
description: VMWare to Openstack / Openshift migration kit
license:
  - Apache-2.0
tags:
  - cloud
  - infrastructure
  - openstack
  - vmware
  - migrations
dependencies:
  openstack.cloud: ">=2.0.0"
  os_migrate.os_migrate: ">=0.0.1"
repository: "https://github.com/os-migrate/vmware-migration-kit"
homepage: "https://github.com/os-migrate/vmware-migration-kit"
issues: "https://github.com/os-migrate/vmware-migration-kit/issues"
build_ignore:
  - .venv
  - .ansible
  - .pytest_cache
  - tests/output
  - tests/__pycache__
  - aee/context
