collections:
  - name: community.crypto
    version: ">=1.4.0"
  - name: community.general
    version: "<5.0.0"
  - name: openstack.cloud
    version: ">=2.0.0"
  - name: os_migrate.os_migrate
    version: ">=0.0.1"
  - name: community.vmware
    version: ">=1.0.0"
