collections:
  - name: openstack.cloud
    version: ">=2.0.0"
  - name: os_migrate.os_migrate
    version: ">=0.0.1"
  - name: vmware.vmware
    version: ">=2.4.0"
  - name: vmware.vmware_rest
    version: ">=4.9.0"
