---
- name: Extract macs addresses for non mapped networks
  when:
    - not import_workloads_used_mapped_networks
  block:
    - name: Read macs file
      ansible.builtin.slurp:
        src: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/macs.json"
      register: macs_file

    - name: Parse JSON content
      ansible.builtin.set_fact:
        macs_list: "{{ macs_file.content | b64decode | from_json | map(attribute='mac') | list }}"

    - name: Create import_workload template
      ansible.builtin.template:
        src: "network_config.sh.j2"
        dest: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/network_config.sh"
        mode: '0755'
        comment_start_string: '{='
        comment_end_string: '=}'

- name: Extract macs addresses for mapped networks
  when:
    - import_workloads_used_mapped_networks
  block:
    - name: Read macs file
      ansible.builtin.slurp:
        src: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/nics.json"
      register: nics_file

    - name: Parse JSON content
      ansible.builtin.set_fact:
        nics_list: "{{ nics_file.content | b64decode | from_json }}"

    - name: Extract MAC addresses
      ansible.builtin.set_fact:
        macs_list: "{{ nics_list | map(attribute='mac') | list }}"

    - name: Create import_workload template
      ansible.builtin.template:
        src: "network_config.sh.j2"
        dest: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/network_config.sh"
        mode: '0755'
        comment_start_string: '{='
        comment_end_string: '=}'

- name: Read the JSON file
  ansible.builtin.slurp:
    src: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/guest_info.json"
  register: guest_info

- name: Parse JSON content
  ansible.builtin.set_fact:
    instance_data: "{{ guest_info.content | b64decode | from_json }}"

- name: Extract vddkpath from guest_info.json
  ansible.builtin.set_fact:
    vddkpath: "{{ instance_data.instance.hw_folder }}"

- name: Migrate Guest from Vmware using nbdkit
  os_migrate.vmware_migration_kit.migrate.migrate:
    dst_cloud: "{{ dst_cloud }}"
    user: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    server: "{{ vcenter_hostname }}"
    vmname: "{{ vm_name }}"
    osmdatadir: "{{ os_migrate_vmw_data_dir }}"
    firstboot: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/network_config.sh"
    vddkpath: "{{ vddkpath }}"
    usesocks: "{{ import_workloads_use_socks | bool }}"
    cbtsync: "{{ import_workloads_cbt_sync | bool }}"
    # convhostname: "{{ conv_host_name }} | default(omit) }}"
  register: migrate_output

- name: Set fact for disk ID
  ansible.builtin.set_fact:
    volume_uuid: "{{ migrate_output.id }}"

- name: Get volume metadata info
  register: volume_info_metadata
  os_migrate.vmware_migration_kit.volume_metadata_info.volume_metadata_info:
    dst_cloud: "{{ dst_cloud }}"
    volume_id: "{{ uuid }}"
  loop: "{{ volume_uuid }}"
  loop_control:
    loop_var: uuid

- name: Set fact for volume metadata
  ansible.builtin.set_fact:
    import_workloads_converted: "{{ volume_info_metadata.results[0].converted }}"
