namespace: os_migrate
name: vmware_migration_kit
version: 1.3.4
readme: README.md
authors:
  - Mathieu Bultel <mat.bultel@gmail.com>
description: VMWare to Openstack / Openshift migration kit
license:
  - Apache-2.0
tags:
  - cloud
  - infrastructure
  - openstack
  - vmware
  - migrations
dependencies:
  community.crypto: '>=1.4.0'
  community.general: '<5.0.0'
  openstack.cloud: '>=2.0.0'
  os_migrate.os_migrate: '>=0.0.1'
  community.vmware: '>=1.0.0'
  ansible.posix: '>=2.0.0'
repository: 'https://github.com/os-migrate/vmware-migration-kit'
homepage: 'https://github.com/os-migrate/vmware-migration-kit'
issues: 'https://github.com/os-migrate/vmware-migration-kit/issues'
