collections:
  - name: vmware.vmware
    version: 2.4.0
  - name: vmware.vmware_rest
    version: 4.9.0
  - name: os_migrate.vmware_migration_kit
    type: file
    source: tmp/os_migrate-vmware_migration_kit-2.1.7.tar.gz
