collections:
  - name: openstack.cloud
    version: 2.2.0
  - name: os_migrate.os_migrate
    version: 1.0.1
  - name: vmware.vmware
    version: 2.4.0
  - name: vmware.vmware_rest
    version: 4.9.0
  - name: os_migrate.vmware_migration_kit
    type: file
    source: tmp/os_migrate-vmware_migration_kit-2.0.9.tar.gz
