import_workloads_use_socks: "{{ use_socks | default(true) | bool }}"
import_workloads_cbt_sync: "{{ cbt_sync | default(false) | bool }}"
import_workloads_converted: "{{ converted | default(false) | bool }}"

import_workloads_used_mapped_networks: "{{ used_mapped_networks | default(false) | bool }}"
import_workloads_image_metadata:
  - hw_rng_model='virtio'
  - os_type='linux'
  - hw_vif_model='virtio'
  - hw_scsi_model='virtio-scsi'
  - hw_qemu_guest_agent='True'
  - hw_disk_bus='scsi'
  - os_distro='rhel'
  - hw_machine_type='q35'
  - hw_firmware_type='uefi'
  - hw_boot_mode='uefi'
  - cinder_img_volume_type='rhcs6-gp3'
