---
- name: Check connectivity to vCenter and OpenStack endpoints for each VM
  os_migrate.vmware_migration_kit.check_connectivity.check_connectivity:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
    timeout: "{{ connectivity_check_timeout | default(10) }}"
    vmname: "{{ item }}"
  register: connectivity_result
  failed_when: connectivity_result.failed is defined and connectivity_result.failed
  changed_when: false
  loop: "{{ vms_list }}"

- name: Display connectivity check results
  ansible.builtin.debug:
    msg: "Connectivity check for {{ item.item }}: {{ item.msg }}"
  loop: "{{ connectivity_result.results }}"
