- name: Export vmware metadata
  hosts: migrator
  vars:
    vms: "{{ vms_list }}"
  tasks:
    - name: Convert vmware metadata to openstack flavors
      ansible.builtin.include_role:
        name: os_migrate.vmware_migration_kit.convert_metadata
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm_name
      vars:
        vm_info_path: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/vm_info.json"
        guest_info_path: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/guest_info.json"
        disk_info_path: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/disk_info.json"
        flavor_name_path: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/flavors.yml"
        network_info_path: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/network_info.json"
        import_workloads_path: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/import_workloads.json"

    - name: Import flavors from YAML
      os_migrate.vmware_migration_kit.import_flavor:
        cloud: "{{ dst_cloud }}"
        flavors_file: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/flavors.yml"
      register: imported_flavors
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm_name
      when: create_flavor

- name: Sync to conversion host
  hosts: conversion_host
  vars:
    os_migrate_vmw_data_dir: /opt/os-migrate
    vms: "{{ vms_list }}"
  tasks:
    - name: Sync to conversion host
      become: true
      ansible.builtin.copy:
        src: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}"
        dest: "{{ os_migrate_vmw_data_dir }}"
        mode: preserve
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm_name
      when: copy_metadata_to_conv_host | default(false) | bool
