---
- name: Setup requirements
  hosts: migrator
  tasks:
    - name: Copy clouds.yaml to os-migrate data dir
      ansible.builtin.copy:
        src: "{{ lookup('env', 'HOME') }}/.config/openstack/clouds.yaml"
        dest: "{{ os_migrate_vmw_data_dir }}"
        mode: '0644'
      when: not already_deploy_conversion_host

    - name: Make sure required package are installed
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - python3
        - python3-pip
      when: not runner_from_aee | default(false)

    - name: Install openstacksdk
      ansible.builtin.pip:
        name: "{{ item }}"
      become: true
      with_items:
        - openstacksdk>1.0.0
        - requests
        - pyVim
        - pyVmomi
      when: not runner_from_aee | default(false)
