name: Ansible Doc Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  doc-validation:
    name: Ansible Doc Validation
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build collection
        run: make build

      - name: Run ansible-doc validation
        run: make test-ansible-doc
