name: Go Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Go Unit Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libnbd-dev pkg-config
      - name: Run Go unit tests
        run: go test -v ./...